version: 2

models:
  - name: dim_customers
    description: "Customer dimension table with surrogate keys"
    columns:
      - name: customer_key
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null]

  - name: dim_products
    description: "Product dimension table with surrogate keys"
    columns:
      - name: product_key
        tests: [unique, not_null]
      - name: product_id
        tests: [not_null]

  - name: fact_sales
    description: "Fact table containing sales transactions"
    columns:
      - name: order_number
        tests: [not_null]
      - name: product_key
        tests: [not_null]
      - name: customer_key
        tests: [not_null]
